### ISSUE TITLE
gRPC dependencies

### ISSUE THREAD

**Issue by codeYann** [codeYann/tiny-rpc#3]
# TODO
- [x] Installing protobuf
- [x] Installing gPRC lib
- [x] Installing protoc-gen-go-grpc
- [x] Installing protobuf protoc-gen-go-grpc

**Comment by codeYann** [comment]
# Status

Done!
